/* NÚMEROS DE CONEXÕES */

SHOW STATUS LIKE 'Threads_connected';

/* MOSTRAR PROCESSOS */

SHOW FULL PROCESSLIST;

/* CRIA SCRIPT PARA ELIMINAR PROCESSOS DE UM DATABASE ESPECÍFICO */

SELECT
	P.ID,
    P.USER,
    P.HOST,
    P.DB,
    P.COMMAND,
    P.TIME,
    P.STATE,
    P.INFO,
	CONCAT('KILL ',P.ID,';') AS KILL_CMD
FROM
	INFORMATION_SCHEMA.PROCESSLIST P
WHERE
	P.DB = 'DATABASE_NAME'
ORDER BY
	ID;